### ISSUE TITLE
建议提供恢复按钮

### ISSUE THREAD

**Issue by YCF** [Return-Log/Drive-Icon-Manager#1]
只能删除，应该叫 Remover，不能叫 Manager ，哈

**Comment by Return-Log** [comment]
感谢你的严谨，因为考虑到这种图标一般没人想恢复就没有做这个功能，收到你的建议，后续我会添加的。
祝你愉快！❤️

**Comment by Return-Log** [comment]
备份功能已加入，详见 v2.1 更新
