### ISSUE TITLE
能否支持移除 iCloud 照片

### ISSUE THREAD

**Issue by colind0pe** [Return-Log/Drive-Icon-Manager#2]
能否支持移除 iCloud 照片，如图，目前识别不到
![image](https://github.com/user-attachments/assets/56f4b7fe-45d1-4958-a72e-225ec089bd41)

**Comment by Return-Log** [comment]
我会在下次更新中添加❤️

**Comment by Return-Log** [comment]
您可以试一下v2.2更新，我查到iCloud和百度网盘一样在HKEY_LOCAL_MACHINE注册表写入，简单改了一下判断逻辑，这回应该可以。
祝你愉快!

**Comment by colind0pe** [comment]
> 您可以试一下v2.2更新，我查到iCloud和百度网盘一样在HKEY_LOCAL_MACHINE注册表写入，简单改了一下判断逻辑，这回应该可以。 祝你愉快!

可以了，感谢感谢~
