### ISSUE TITLE
注册表权限禁止后改不回去了，佬有方法吗

### ISSUE THREAD

**Issue by 768896** [Return-Log/Drive-Icon-Manager#3]
![Snipaste_2024-08-27_12-05-03](https://github.com/user-attachments/assets/8c4128e8-5d38-4639-a634-01d83e36dae4)
![Snipaste_2024-08-27_12-08-18](https://github.com/user-attachments/assets/90d5bb7e-9f91-47ef-aa90-2b85ea7364bb)
![image](https://github.com/user-attachments/assets/5eb12385-2682-49ee-a131-d206b041f114)

**Comment by 768896** [comment]
![image](https://github.com/user-attachments/assets/4c9b4829-2c90-412f-bded-29c50fb58dbd)
弹出了一个弹窗

**Comment by Return-Log** [comment]
第二张图的权限设置‘组’那里要选当前电脑登陆的用户，比如现在登录的用户是Admin就选Admin，然后把两个拒绝取消勾选再点应用就行。
或者你挨个点‘组’哪个被勾选’拒绝‘取消勾选就行。
祝你愉快！

**Comment by 768896** [comment]
好了，谢谢
![image](https://github.com/user-attachments/assets/9ef4a8cb-b44f-4dcc-8922-b92fe7d6d28a)
![image](https://github.com/user-attachments/assets/6e7d0d15-ebb6-42b1-b338-ef13bfc29374)
路径错了，已解决
